server:
  port: 8080
spring:
  mvc:
    view:
      suffix: .html
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  devtools:
      restart:
        enabled: false #是否开启开发者工具（true/false）
        additional-paths: src/main/java
        exclude: static/**,WEB-INF/view/**

  # H2 DATABASE CONFIG
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    schema: classpath:/db/schema.sql
    data: classpath:/db/data.sql
    # url: jdbc:h2:mem:resource
    url: jdbc:h2:./resource
    username: root
    password: root
    platform: h2
    initialization-mode: always
    continue-on-error: true
  h2:
    console:
     enabled: true
     path: /console
    settings:
     web-allow-others: true

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.resource.operate.resourceDownload.model
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: h2
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
##logging
logging:
  pattern:
    console: "%d - %msg%n"
  path: logs/
  file: file.log